aws_stack_name="pan-demo"
aws_region="us-west-2"
aws_access_key_id="XXXXXXXXXXXXX"
aws_secret_access_key="XXXXXXXXXXXXXXX"
aws_session_token="XXXXXXXX"
panfw_bootstrap_bucket="<s3 bucket where PAN config stored>"
aws_auth_key="<optional>"
aws_allowed_cidr=["0.0.0.0/0"]
aws_license_server="3.15.161.10"
