aws_stack_name="pan-demo"
aws_region="us-west-2"
aws_access_key_id="XXXXXXXXXXXXXXXX"
aws_secret_access_key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
panfw_bootstrap_bucket="<s3 bucket name where pan config stored>"
