aws_stack_name="pan-demo"
aws_access_key="XXXXXXXXXXXXXXXX"
aws_secret_key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
aws_auth_key="<ssh key>"
panfw_bootstrap_bucket="<s3 bucket name where pan config stored>"
